#include "houtputbackendROOT.h"


// this output backend is broken badly!!! i will maybe fix this in the future, but it currently has no priority
void HOutPutBackEndROOT::dumpEvent()
{
//   eventTree->Fill();
}

void HOutPutBackEndROOT::writeHeader()
{
//   eventTree->Branch("Parameters","HParams",paramMan->getStruct());
}


void HOutPutBackEndROOT::setParams(HParamManager* _params)
{
//     HOutPutBackEnd::setParams(_params);
}


void HOutPutBackEndROOT::closeFile()
{
//   eventFile = new TFile(fileName.c_str(),"RECREATE");
//   eventTree->Write();
//   eventFile->Flush();
//   eventFile->Write();
//   eventFile->Close();
//   delete eventFile;
}



void HOutPutBackEndROOT::initFile(std::string _fileName, HEvent* _eventPointer)
{
//   eventPointer=_eventPointer;
//   fileName = _fileName;
//   fileName += ".root";
//   eventTree = new TTree("eventTree", "Events generated by HEPGen_C");
//   eventTree->Branch("Events","HEventData",eventPointer->getStruct());
//
//
//
}
